server:
  port: 3344

spring:
  application:
    name: springcloud_config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mshuainan/spring_cloud_config.git #GitHub上面的git仓库名字


