server:
  port: 9527

spring:
  application:
    name: springcloud_zuul_gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway_9527.com
    prefer-ip-address: true

zuul:
  #ignored-services: microservicecloud-dept
  prefix: /shnma
  ignored-services: "*"
  routes:
    mydept.serviceId: springcloud-dept
    mydept.path: /mydept/**

info:
  app.name: shnma_springcloud
  company.name: www.shnma.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

